### ISSUE TITLE
errors when execute `sbt run'

### ISSUE THREAD

**Issue by nijianmo** [allenai/essential-terms#1]
Thanks for publishing the code!

I have tried to run the code. At first I met some dependency issues when running `sbt compile`. I checked the post https://github.com/allenai/semanticilp/issues/3 and added the related dependencies (textilp-dependencies, edu.cmu) into ./ivy2. The code seems compiled successfully.

However, when I ran `sbt run`, following errors occurred. I tried to solve the duplicate dependency issue adding exclusion in the `build.sbt` file. For example, modified line `wumpusClient exclude("edu.stanford.nlp", "stanford-corenlp, "org.slf4j"),` but it did not succeed.

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /home/user/essential-terms/project
[info] Loading settings for project essential-terms from build.sbt ...
[info] Set current project to essential-terms (in build file:/home/user/essential-terms/)
[info] Packaging /home/user/essential-terms/target/scala-2.11/essential-terms_2.11-1.2.jar ...
[info] Done packaging.
[info] Running (fork) org.allenai.ari.solvers.termselector.evaluation.EvaluationApp
[error] SLF4J: Class path contains multiple SLF4J bindings.
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_772e6129/target/3b6b8927/wumpus-client-assembly-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_772e6129/target/bd245d67/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_772e6129/target/9865cf69/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] INFO  [2018-08-02 21:10:25,361] akka.event.slf4j.Slf4jLogger: Slf4jLogger started
[error] Exception in thread "main" java.lang.IllegalArgumentException:
[error] USAGE:
[error]  run 1  <classifier model>  (TrainAndTestMainLearner)
[error]  run 2  <classifier model> <train/dev>  (LoadAndTestMainLearner)
[error]  run 3  <classifier model>  (TrainAndTestBaseline)
[error]  run 4  <classifier model>  (TestWithAristoQuestion)
[error]  run 5  <classifier model>  (CacheSalienceScores)
[error]  run 6  <classifier model>  (PrintMistakes)
[error]  run 7  <classifier model>  (PrintFeatures)
[error]  run 8  <max/sum>           (TestSalienceBaslineWithAristoQuestion)
[error]  run 9 <max/sum>            (TestSalienceBasline)
[error]  run 10 <maxSalience/sumSalience/wordBaseline/lemmaBaseline/expanded> <classifier model>  (TuneClassifiers)
[error]  run 11 <classifier model>  (PrintStatistics)
[error]  run 12 <maxSalience/sumSalience/wordBaseline/lemmaBaseline/expanded> <classifier model>  (TestClassifierAcrossThresholds)
[error]  run 13 <classifier model>  (SaveRedisAnnotationCache)
[error]         at org.allenai.ari.solvers.termselector.evaluation.EvaluationApp$.main(EvaluationApp.scala:548)
[error]         at org.allenai.ari.solvers.termselector.evaluation.EvaluationApp.main(EvaluationApp.scala)
```

When I ran `sbt console` to directly use the model as described in readme file, it also did not work.
```
[info] Starting scala interpreter...
Welcome to Scala version 2.11.5 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions to have them evaluated.
Type :help for more information.

scala> // loading the models

scala> val salienceBaselines = SalienceLearner.makeNewLearners()
<console>:7: error: not found: value SalienceLearner
       val salienceBaselines = SalienceLearner.makeNewLearners()
                               ^
```

Do you have any idea how those to solve these?
Thanks!

**Comment by danyaljj** [comment]
Hello there!  In your first log, seems like everything compiles just fine (notice the content after "USAGE:").

**Comment by nijianmo** [comment]
Hi, thanks for the swift reply! That's helpful.

I tried to execute `run 9` to run the TestSalienceBasline. There seems to be a connection error. Any clue about this?

```
[info] INFO  [2018-08-02 21:36:45,640] org.allenai.datastore.Datastore: Downloaded org.allenai.termselector/salienceCache-v3.txt from the public datastore. 139 MB bytes read.
[info] ERROR [2018-08-02 21:36:45,885] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[error] Exception in thread "main" scala.MatchError:  (of class java.lang.String)
[error]         at org.allenai.ari.solvers.termselector.evaluation.EvaluationApp.testSalienceLearner(EvaluationApp.scala:84)
[error]         at org.allenai.ari.solvers.termselector.evaluation.EvaluationApp$.main(EvaluationApp.scala:584)
[error]         at org.allenai.ari.solvers.termselector.evaluation.EvaluationApp.main(EvaluationApp.scala)
[info] ERROR [2018-08-02 21:36:50,908] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:36:55,934] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
```

**Comment by danyaljj** [comment]
Here is the problem: the system is this remote system server to extract PMI/Salience scores. That server is within AI2's VPN wall, and inaccessible for anyone outside. Hence you cannot run the Salience/PMI baselines and the full ET classifier (which uses salience/PMI features). 

However, I have included a version of the classifier which does not use PMI features. The system is referred to as "direct-answer" ET. This snippet shows how to run it: 
https://github.com/allenai/essential-terms/blob/stand-alone/src/main/scala/org/allenai/ari/solvers/termselector/evaluation/EvaluationApp.scala#L100-L109


Please check if that works for you.

**Comment by nijianmo** [comment]
Thanks for the reply! However, the "direct-answer" ET seems also need to access that server.

I added a switch case in `EvaluationApp.scala`  as follows, then run `run 14 SVM-directAnswer`. According to the log, the code still failed to connect the server.
```
case "14" =>
        val essentialTermsApp = new EvaluationApp(loadModelType = LoadFromDatastore, arg1)
        essentialTermsApp.testLearnerWithSampleAristoQuestionDirectAnswer()
```
error log:
```
sbt:essential-terms> run 14 SVM-directAnswer
[info] Running (fork) org.allenai.ari.solvers.termselector.evaluation.EvaluationApp 14 SVM-directAnswer
[error] SLF4J: Class path contains multiple SLF4J bindings.
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_6f800571/target/3b6b8927/wumpus-client-assembly-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_6f800571/target/bd245d67/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/tmp/sbt_6f800571/target/9865cf69/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] INFO  [2018-08-02 21:41:19,204] akka.event.slf4j.Slf4jLogger: Slf4jLogger started
[info] ERROR [2018-08-02 21:41:23,597] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:41:28,644] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:41:33,900] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] INFO  [2018-08-02 21:41:34,336] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnersurfaceForm-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,347] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnersurfaceForm-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,349] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnerlemma-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,352] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnerlemma-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,354] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnerPosConjLemma-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,356] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnerPosConjLemma-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,358] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerWordFormConjNer-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,361] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerWordFormConjNer-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,362] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerWordFormConjNerCojPos-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,365] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerWordFormConjNerCojPos-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,366] o.a.a.s.t.learners.BaselineLearner: Reading model file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerLemmaPair-dev.lc from local path.
[info] INFO  [2018-08-02 21:41:34,370] o.a.a.s.t.learners.BaselineLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.BaselineLearnerbaselineLearnerLemmaPair-dev.lex from local path.
[info] INFO  [2018-08-02 21:41:34,434] o.a.a.s.t.learners.ExpandedLearner: Reading model file org.allenai.ari.solvers.termselector.learners.ExpandedLearnerSVM-directAnswer.lc from local path.
[info] INFO  [2018-08-02 21:41:34,446] o.a.a.s.t.learners.ExpandedLearner: Reading lexicon file org.allenai.ari.solvers.termselector.learners.ExpandedLearnerSVM-directAnswer.lex from local path.
[info] INFO  [2018-08-02 21:41:34,546] e.i.c.c.a.h.IllinoisPOSHandler: Loading POS model..
[info] INFO  [2018-08-02 21:41:34,828] e.i.c.c.a.h.IllinoisPOSHandler: POS Tagger ready
[info] INFO  [2018-08-02 21:41:34,964] e.i.c.c.a.h.IllinoisChunkerHandler: Loading Chunker model..
[info] INFO  [2018-08-02 21:41:35,784] e.i.c.c.a.h.IllinoisChunkerHandler: Chunker ready
[info] INFO  [2018-08-02 21:41:35,797] e.i.c.c.ner.LbjTagger.Parameters: Loading TreeGazetteers at length 5
[info] ERROR [2018-08-02 21:41:38,918] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:41:44,246] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:41:49,268] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] INFO  [2018-08-02 21:41:50,893] e.i.cs.cogcomp.ner.NERAnnotator: Reading model file: ner/models/CoNLL.model.level1
[info] INFO  [2018-08-02 21:41:51,661] e.i.cs.cogcomp.ner.NERAnnotator: Reading model file: ner/models/CoNLL.model.level2
[error] Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.7 sec].
[error] Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.1 sec].
[info] ERROR [2018-08-02 21:41:54,292] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:41:59,308] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:07,096] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:12,115] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:17,139] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:22,159] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:27,179] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2018-08-02 21:42:32,199] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
```

**Comment by danyaljj** [comment]
I created [a file](https://github.com/allenai/essential-terms/blob/stand-alone/src/main/scala/org/allenai/ari/solvers/termselector/evaluation/RunDirectAnswerAnnotator.scala) for you to show how to run the direct-answer annotator. If you see any warnings with regards to wumpus you can ignore it. Please give it a try and let me know if it works for you.

**Comment by nijianmo** [comment]
Awesome, thanks for the update. This one works for me!

**Comment by sylxjtu** [comment]
Thanks for publishing the code! I tried the steps above to resolve dependencies, on running `sbt 'runMain org.allenai.ari.solvers.termselector.evaluation.out.RunDirectAnswerAnnotator'`, the similar problem appears, here's the log that command produced. 

```
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading global plugins from C:\Users\Dell\.sbt\1.0\plugins
[info] Loading project definition from C:\Users\Dell\Desktop\keyword\essential-terms\project
[info] Loading settings for project essential-terms from build.sbt ...
[info] Set current project to essential-terms (in build file:/C:/Users/Dell/Desktop/keyword/essential-terms/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running (fork) org.allenai.ari.solvers.termselector.evaluation.out.RunDirectAnswerAnnotator
[error] SLF4J: Class path contains multiple SLF4J bindings.
[error] SLF4J: Found binding in [jar:file:/C:/Users/Dell/AppData/Local/Temp/sbt_23a5b3a9/target/3b6b8927/wumpus-client-assembly-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/C:/Users/Dell/AppData/Local/Temp/sbt_23a5b3a9/target/bd245d67/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/C:/Users/Dell/AppData/Local/Temp/sbt_23a5b3a9/target/9865cf69/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] INFO  [2019-08-02 21:26:46,140] akka.event.slf4j.Slf4jLogger: Slf4jLogger started
[error] WARNING: An illegal reflective access operation has occurred
[error] WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/Users/Dell/AppData/Local/Temp/sbt_23a5b3a9/target/0f990a43/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[error] WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
[error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[error] WARNING: All illegal access operations will be denied in a future release
[info] ERROR [2019-08-02 21:26:47,114] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[error] Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
[error]         at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[error]         at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[error]         at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[error]         at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
[error]         at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
[error]         at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
[error]         at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
[error]         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
[error]         at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:941)
[error]         at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:957)
[error]         at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:995)
[error]         at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:998)
[error]         at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]         at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:301)
[error]         at scala.collection.AbstractIterator.toMap(Iterator.scala:1202)
[error]         at org.allenai.ari.solvers.termselector.Sensors.salienceMap$lzycompute(Sensors.scala:71)
[error]         at org.allenai.ari.solvers.termselector.Sensors.salienceMap(Sensors.scala:63)
[error]         at org.allenai.ari.solvers.termselector.Sensors.<init>(Sensors.scala:30)
[error]         at org.allenai.ari.solvers.termselector.evaluation.out.RunDirectAnswerAnnotator$.main(RunDirectAnswerAnnotator.scala:27)
[error]         at org.allenai.ari.solvers.termselector.evaluation.out.RunDirectAnswerAnnotator.main(RunDirectAnswerAnnotator.scala)
[info] ERROR [2019-08-02 21:26:52,129] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:26:57,140] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:02,159] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:07,168] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:12,183] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:17,207] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:22,226] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:27,255] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:32,274] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:37,300] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:42,307] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:47,325] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:52,345] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:27:57,367] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:02,385] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:07,411] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:12,416] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:17,440] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:22,448] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:27,455] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:32,477] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:37,501] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:42,507] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:47,528] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:52,545] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:28:57,570] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:29:02,577] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
[info] ERROR [2019-08-02 21:29:07,599] o.allenai.wumpus.client.ProtocolFsm: Failed to connect to Wumpus server waterloo.corp.ai2:9215. Retrying in 5000 milliseconds
```

Do you have any idea how those to solve these?
Thanks!
